
name: 🧡 Mantener mi Racha Viva

on:
  schedule:
    # Corre diario a las 03:10 UTC (después del WakaTime)
    - cron: "10 3 * * *"
  workflow_dispatch:

jobs:
  keep-streak-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Actualizar archivo keepalive
        run: |
          echo "Última actualización: $(date -u)" > .keepalive.txt

      - name: Commit y Push
        run: |
          git config user.name "jorge-ivan-jimenez-reyes"
          git config user.email "0251139@up.edu.mx"
          git add .keepalive.txt
          git commit -m "chore: actualización diaria automática" || echo "Sin cambios"
          git push
