name: 📈 Actualizar WakaTime

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: 

jobs:
  update-waka-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          COMMIT_BY_ME: "False"  

          #  
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROFILE_VIEWS: "False"

          SHOW_TIME: "True"         
          SHOW_TOTAL_CODE_TIME: "True" 
